apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: vovhubdoc/python-app:e6e93a3a00ea930df5f1b10b4af8c157f1d1da0b
        ports:
        - containerPort: 5000
